/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as ExamplesSlugRouteImport } from './routes/examples/$slug'
import { Route as FdeIndexRouteImport } from './routes/fde/index'
import { Route as FdeSlugRouteImport } from './routes/fde/$slug'
import { Route as HldIndexRouteImport } from './routes/hld/index'
import { Route as HldSlugRouteImport } from './routes/hld/$slug'
import { Route as JavaIndexRouteImport } from './routes/java/index'
import { Route as JavaSlugRouteImport } from './routes/java/$slug'
import { Route as LldIndexRouteImport } from './routes/lld/index'
import { Route as LldSlugRouteImport } from './routes/lld/$slug'
import { Route as PlaygroundsIndexRouteImport } from './routes/playgrounds/index'
import { Route as PlaygroundsSlugRouteImport } from './routes/playgrounds/$slug'
import { Route as PythonIndexRouteImport } from './routes/python/index'
import { Route as PythonSlugRouteImport } from './routes/python/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSlugRoute = ExamplesSlugRouteImport.update({
  id: '/examples/$slug',
  path: '/examples/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FdeIndexRoute = FdeIndexRouteImport.update({
  id: '/fde/',
  path: '/fde/',
  getParentRoute: () => rootRouteImport,
} as any)
const FdeSlugRoute = FdeSlugRouteImport.update({
  id: '/fde/$slug',
  path: '/fde/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HldIndexRoute = HldIndexRouteImport.update({
  id: '/hld/',
  path: '/hld/',
  getParentRoute: () => rootRouteImport,
} as any)
const HldSlugRoute = HldSlugRouteImport.update({
  id: '/hld/$slug',
  path: '/hld/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JavaIndexRoute = JavaIndexRouteImport.update({
  id: '/java/',
  path: '/java/',
  getParentRoute: () => rootRouteImport,
} as any)
const JavaSlugRoute = JavaSlugRouteImport.update({
  id: '/java/$slug',
  path: '/java/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LldIndexRoute = LldIndexRouteImport.update({
  id: '/lld/',
  path: '/lld/',
  getParentRoute: () => rootRouteImport,
} as any)
const LldSlugRoute = LldSlugRouteImport.update({
  id: '/lld/$slug',
  path: '/lld/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsIndexRoute = PlaygroundsIndexRouteImport.update({
  id: '/playgrounds/',
  path: '/playgrounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsSlugRoute = PlaygroundsSlugRouteImport.update({
  id: '/playgrounds/$slug',
  path: '/playgrounds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonIndexRoute = PythonIndexRouteImport.update({
  id: '/python/',
  path: '/python/',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonSlugRoute = PythonSlugRouteImport.update({
  id: '/python/$slug',
  path: '/python/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/welcome': typeof WelcomeRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/fde/$slug': typeof FdeSlugRoute
  '/hld/$slug': typeof HldSlugRoute
  '/java/$slug': typeof JavaSlugRoute
  '/lld/$slug': typeof LldSlugRoute
  '/playgrounds/$slug': typeof PlaygroundsSlugRoute
  '/python/$slug': typeof PythonSlugRoute
  '/examples/': typeof ExamplesIndexRoute
  '/fde/': typeof FdeIndexRoute
  '/hld/': typeof HldIndexRoute
  '/java/': typeof JavaIndexRoute
  '/lld/': typeof LldIndexRoute
  '/playgrounds/': typeof PlaygroundsIndexRoute
  '/python/': typeof PythonIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/welcome': typeof WelcomeRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/fde/$slug': typeof FdeSlugRoute
  '/hld/$slug': typeof HldSlugRoute
  '/java/$slug': typeof JavaSlugRoute
  '/lld/$slug': typeof LldSlugRoute
  '/playgrounds/$slug': typeof PlaygroundsSlugRoute
  '/python/$slug': typeof PythonSlugRoute
  '/examples': typeof ExamplesIndexRoute
  '/fde': typeof FdeIndexRoute
  '/hld': typeof HldIndexRoute
  '/java': typeof JavaIndexRoute
  '/lld': typeof LldIndexRoute
  '/playgrounds': typeof PlaygroundsIndexRoute
  '/python': typeof PythonIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/welcome': typeof WelcomeRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/fde/$slug': typeof FdeSlugRoute
  '/hld/$slug': typeof HldSlugRoute
  '/java/$slug': typeof JavaSlugRoute
  '/lld/$slug': typeof LldSlugRoute
  '/playgrounds/$slug': typeof PlaygroundsSlugRoute
  '/python/$slug': typeof PythonSlugRoute
  '/examples/': typeof ExamplesIndexRoute
  '/fde/': typeof FdeIndexRoute
  '/hld/': typeof HldIndexRoute
  '/java/': typeof JavaIndexRoute
  '/lld/': typeof LldIndexRoute
  '/playgrounds/': typeof PlaygroundsIndexRoute
  '/python/': typeof PythonIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/welcome'
    | '/examples/$slug'
    | '/fde/$slug'
    | '/hld/$slug'
    | '/java/$slug'
    | '/lld/$slug'
    | '/playgrounds/$slug'
    | '/python/$slug'
    | '/examples/'
    | '/fde/'
    | '/hld/'
    | '/java/'
    | '/lld/'
    | '/playgrounds/'
    | '/python/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/welcome'
    | '/examples/$slug'
    | '/fde/$slug'
    | '/hld/$slug'
    | '/java/$slug'
    | '/lld/$slug'
    | '/playgrounds/$slug'
    | '/python/$slug'
    | '/examples'
    | '/fde'
    | '/hld'
    | '/java'
    | '/lld'
    | '/playgrounds'
    | '/python'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/welcome'
    | '/examples/$slug'
    | '/fde/$slug'
    | '/hld/$slug'
    | '/java/$slug'
    | '/lld/$slug'
    | '/playgrounds/$slug'
    | '/python/$slug'
    | '/examples/'
    | '/fde/'
    | '/hld/'
    | '/java/'
    | '/lld/'
    | '/playgrounds/'
    | '/python/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  WelcomeRoute: typeof WelcomeRoute
  ExamplesSlugRoute: typeof ExamplesSlugRoute
  FdeSlugRoute: typeof FdeSlugRoute
  HldSlugRoute: typeof HldSlugRoute
  JavaSlugRoute: typeof JavaSlugRoute
  LldSlugRoute: typeof LldSlugRoute
  PlaygroundsSlugRoute: typeof PlaygroundsSlugRoute
  PythonSlugRoute: typeof PythonSlugRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
  FdeIndexRoute: typeof FdeIndexRoute
  HldIndexRoute: typeof HldIndexRoute
  JavaIndexRoute: typeof JavaIndexRoute
  LldIndexRoute: typeof LldIndexRoute
  PlaygroundsIndexRoute: typeof PlaygroundsIndexRoute
  PythonIndexRoute: typeof PythonIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$slug': {
      id: '/examples/$slug'
      path: '/examples/$slug'
      fullPath: '/examples/$slug'
      preLoaderRoute: typeof ExamplesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fde/': {
      id: '/fde/'
      path: '/fde'
      fullPath: '/fde/'
      preLoaderRoute: typeof FdeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fde/$slug': {
      id: '/fde/$slug'
      path: '/fde/$slug'
      fullPath: '/fde/$slug'
      preLoaderRoute: typeof FdeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hld/': {
      id: '/hld/'
      path: '/hld'
      fullPath: '/hld/'
      preLoaderRoute: typeof HldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hld/$slug': {
      id: '/hld/$slug'
      path: '/hld/$slug'
      fullPath: '/hld/$slug'
      preLoaderRoute: typeof HldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/java/': {
      id: '/java/'
      path: '/java'
      fullPath: '/java/'
      preLoaderRoute: typeof JavaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/java/$slug': {
      id: '/java/$slug'
      path: '/java/$slug'
      fullPath: '/java/$slug'
      preLoaderRoute: typeof JavaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lld/': {
      id: '/lld/'
      path: '/lld'
      fullPath: '/lld/'
      preLoaderRoute: typeof LldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lld/$slug': {
      id: '/lld/$slug'
      path: '/lld/$slug'
      fullPath: '/lld/$slug'
      preLoaderRoute: typeof LldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/': {
      id: '/playgrounds/'
      path: '/playgrounds'
      fullPath: '/playgrounds/'
      preLoaderRoute: typeof PlaygroundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/$slug': {
      id: '/playgrounds/$slug'
      path: '/playgrounds/$slug'
      fullPath: '/playgrounds/$slug'
      preLoaderRoute: typeof PlaygroundsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python/': {
      id: '/python/'
      path: '/python'
      fullPath: '/python/'
      preLoaderRoute: typeof PythonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python/$slug': {
      id: '/python/$slug'
      path: '/python/$slug'
      fullPath: '/python/$slug'
      preLoaderRoute: typeof PythonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  WelcomeRoute: WelcomeRoute,
  ExamplesSlugRoute: ExamplesSlugRoute,
  FdeSlugRoute: FdeSlugRoute,
  HldSlugRoute: HldSlugRoute,
  JavaSlugRoute: JavaSlugRoute,
  LldSlugRoute: LldSlugRoute,
  PlaygroundsSlugRoute: PlaygroundsSlugRoute,
  PythonSlugRoute: PythonSlugRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
  FdeIndexRoute: FdeIndexRoute,
  HldIndexRoute: HldIndexRoute,
  JavaIndexRoute: JavaIndexRoute,
  LldIndexRoute: LldIndexRoute,
  PlaygroundsIndexRoute: PlaygroundsIndexRoute,
  PythonIndexRoute: PythonIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
