/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as ExamplesSlugRouteImport } from './routes/examples/$slug'
import { Route as FdeIndexRouteImport } from './routes/fde/index'
import { Route as FdeSlugRouteImport } from './routes/fde/$slug'
import { Route as HldIndexRouteImport } from './routes/hld/index'
import { Route as HldSlugRouteImport } from './routes/hld/$slug'
import { Route as LldIndexRouteImport } from './routes/lld/index'
import { Route as LldSlugRouteImport } from './routes/lld/$slug'
import { Route as PlaygroundsIndexRouteImport } from './routes/playgrounds/index'
import { Route as PlaygroundsSlugRouteImport } from './routes/playgrounds/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSlugRoute = ExamplesSlugRouteImport.update({
  id: '/examples/$slug',
  path: '/examples/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FdeIndexRoute = FdeIndexRouteImport.update({
  id: '/fde/',
  path: '/fde/',
  getParentRoute: () => rootRouteImport,
} as any)
const FdeSlugRoute = FdeSlugRouteImport.update({
  id: '/fde/$slug',
  path: '/fde/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HldIndexRoute = HldIndexRouteImport.update({
  id: '/hld/',
  path: '/hld/',
  getParentRoute: () => rootRouteImport,
} as any)
const HldSlugRoute = HldSlugRouteImport.update({
  id: '/hld/$slug',
  path: '/hld/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LldIndexRoute = LldIndexRouteImport.update({
  id: '/lld/',
  path: '/lld/',
  getParentRoute: () => rootRouteImport,
} as any)
const LldSlugRoute = LldSlugRouteImport.update({
  id: '/lld/$slug',
  path: '/lld/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsIndexRoute = PlaygroundsIndexRouteImport.update({
  id: '/playgrounds/',
  path: '/playgrounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsSlugRoute = PlaygroundsSlugRouteImport.update({
  id: '/playgrounds/$slug',
  path: '/playgrounds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/fde/$slug': typeof FdeSlugRoute
  '/hld/$slug': typeof HldSlugRoute
  '/lld/$slug': typeof LldSlugRoute
  '/playgrounds/$slug': typeof PlaygroundsSlugRoute
  '/examples/': typeof ExamplesIndexRoute
  '/fde/': typeof FdeIndexRoute
  '/hld/': typeof HldIndexRoute
  '/lld/': typeof LldIndexRoute
  '/playgrounds/': typeof PlaygroundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/fde/$slug': typeof FdeSlugRoute
  '/hld/$slug': typeof HldSlugRoute
  '/lld/$slug': typeof LldSlugRoute
  '/playgrounds/$slug': typeof PlaygroundsSlugRoute
  '/examples': typeof ExamplesIndexRoute
  '/fde': typeof FdeIndexRoute
  '/hld': typeof HldIndexRoute
  '/lld': typeof LldIndexRoute
  '/playgrounds': typeof PlaygroundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/fde/$slug': typeof FdeSlugRoute
  '/hld/$slug': typeof HldSlugRoute
  '/lld/$slug': typeof LldSlugRoute
  '/playgrounds/$slug': typeof PlaygroundsSlugRoute
  '/examples/': typeof ExamplesIndexRoute
  '/fde/': typeof FdeIndexRoute
  '/hld/': typeof HldIndexRoute
  '/lld/': typeof LldIndexRoute
  '/playgrounds/': typeof PlaygroundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resources'
    | '/examples/$slug'
    | '/fde/$slug'
    | '/hld/$slug'
    | '/lld/$slug'
    | '/playgrounds/$slug'
    | '/examples/'
    | '/fde/'
    | '/hld/'
    | '/lld/'
    | '/playgrounds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resources'
    | '/examples/$slug'
    | '/fde/$slug'
    | '/hld/$slug'
    | '/lld/$slug'
    | '/playgrounds/$slug'
    | '/examples'
    | '/fde'
    | '/hld'
    | '/lld'
    | '/playgrounds'
  id:
    | '__root__'
    | '/'
    | '/resources'
    | '/examples/$slug'
    | '/fde/$slug'
    | '/hld/$slug'
    | '/lld/$slug'
    | '/playgrounds/$slug'
    | '/examples/'
    | '/fde/'
    | '/hld/'
    | '/lld/'
    | '/playgrounds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourcesRoute: typeof ResourcesRoute
  ExamplesSlugRoute: typeof ExamplesSlugRoute
  FdeSlugRoute: typeof FdeSlugRoute
  HldSlugRoute: typeof HldSlugRoute
  LldSlugRoute: typeof LldSlugRoute
  PlaygroundsSlugRoute: typeof PlaygroundsSlugRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
  FdeIndexRoute: typeof FdeIndexRoute
  HldIndexRoute: typeof HldIndexRoute
  LldIndexRoute: typeof LldIndexRoute
  PlaygroundsIndexRoute: typeof PlaygroundsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$slug': {
      id: '/examples/$slug'
      path: '/examples/$slug'
      fullPath: '/examples/$slug'
      preLoaderRoute: typeof ExamplesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fde/': {
      id: '/fde/'
      path: '/fde'
      fullPath: '/fde/'
      preLoaderRoute: typeof FdeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fde/$slug': {
      id: '/fde/$slug'
      path: '/fde/$slug'
      fullPath: '/fde/$slug'
      preLoaderRoute: typeof FdeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hld/': {
      id: '/hld/'
      path: '/hld'
      fullPath: '/hld/'
      preLoaderRoute: typeof HldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hld/$slug': {
      id: '/hld/$slug'
      path: '/hld/$slug'
      fullPath: '/hld/$slug'
      preLoaderRoute: typeof HldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lld/': {
      id: '/lld/'
      path: '/lld'
      fullPath: '/lld/'
      preLoaderRoute: typeof LldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lld/$slug': {
      id: '/lld/$slug'
      path: '/lld/$slug'
      fullPath: '/lld/$slug'
      preLoaderRoute: typeof LldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/': {
      id: '/playgrounds/'
      path: '/playgrounds'
      fullPath: '/playgrounds/'
      preLoaderRoute: typeof PlaygroundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/$slug': {
      id: '/playgrounds/$slug'
      path: '/playgrounds/$slug'
      fullPath: '/playgrounds/$slug'
      preLoaderRoute: typeof PlaygroundsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourcesRoute: ResourcesRoute,
  ExamplesSlugRoute: ExamplesSlugRoute,
  FdeSlugRoute: FdeSlugRoute,
  HldSlugRoute: HldSlugRoute,
  LldSlugRoute: LldSlugRoute,
  PlaygroundsSlugRoute: PlaygroundsSlugRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
  FdeIndexRoute: FdeIndexRoute,
  HldIndexRoute: HldIndexRoute,
  LldIndexRoute: LldIndexRoute,
  PlaygroundsIndexRoute: PlaygroundsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
